# =============================================================
# LGCM Reproducible Template
# Multi-Group Latent Growth Curve Model (MG-LGCM) for
# longitudinal outcomes by group (4-wave panel, generic demo)
# -------------------------------------------------------------
# DATA NOTICE (READ THIS FIRST):
#   This template uses 100% SYNTHETIC data generated by
#   simulate_data(). It contains NO real records. The data only
#   mirror the *structure* of a generic 4-wave panel design
#   (grouped, covariate-coded, repeated outcomes); the values
#   are fabricated for demonstration and use PLACEHOLDER variable
#   names (grp / cov / y_1..y_4 / z_1..z_4) on purpose, so the
#   free template never reveals a real research data schema.
#   To analyse your own data, replace simulate_data() with your
#   loader and keep the downstream pipeline unchanged.
#
#   The PRODUCTION-READY data format specification and a
#   realistic sample dataset are provided in the paid bundle
#   (see the 5-yuan add-on). Do not look for a real schema here.
#
# WHY THIS TEMPLATE EXISTS:
#   A self-contained, teachable demonstration of the full
#   MG-LGCM workflow (growth model -> measurement invariance
#   -> between-group comparison -> moderation -> model-shape
#   check). Two sections go beyond a naive "fit and report"
#   workflow and are flagged as "CORRECTED DEMO":
#     (a) a full measurement-invariance sequence
#         (configural -> metric -> scalar -> strict), because
#         scalar invariance is the real prerequisite for latent
#         mean comparison;
#     (b) a quadratic-growth comparison, because the linear
#         assumption may mask a non-monotonic trajectory.
# =============================================================

## ---------- 0. Environment & packages ----------
pkgs <- c("lavaan", "semTools", "dplyr", "ggplot2")
new <- pkgs[!(pkgs %in% installed.packages()[, "Package"])]
if (length(new)) install.packages(new)   # MASS ships with R, no install needed
lapply(c(pkgs, "MASS"), library, character.only = TRUE)

set.seed(20260621)


## ---------- 1. simulate_data(): structure-identical, content-fake ----------
#' Generates a synthetic 4-wave panel for demonstration using
#' GENERIC placeholder variable names on purpose (so the free
#' template reveals no real research schema):
#'   - grouping variable: grp (4 levels G1/G2/G3/G4)
#'   - covariate: cov (M/F)
#'   - repeated composite outcome: y_1..y_4 (4 waves)
#'   - repeated single-item outcome: z_1..z_4 (4 waves, used to
#'     demo the per-item invariance chain)
#' Latent intercept/slope means are set to plausible values so the
#' demo output shows group differences, while containing zero real
#' records. The PRODUCTION schema + a realistic sample live in the
#' paid bundle.
simulate_data <- function(n_total = 8000, seed = 20260621, verbose = TRUE) {
  set.seed(seed)

  # group composition (G2 dominates, stands in for a majority group)
  grp_prop <- c(G1 = 0.08, G2 = 0.74, G3 = 0.14, G4 = 0.04)
  n_grp <- round(n_total * grp_prop)

  # latent means (outcome y): i = intercept, s = linear slope
  i_mean <- c(G1 = -0.003, G2 = 0.222, G3 = -0.866, G4 = -1.792)
  s_mean <- c(G1 =  0.075, G2 = 0.006, G3 =  0.161, G4 =  0.296)
  # latent (co)variances (scaled down slightly so the
  # synthetic demo stays well-conditioned: large i_var + the 3*IQR recode in
  # clean_data() would otherwise create fully-empty rows and non-positive-definite
  # models that can destabilise MLR fits)
  i_var <- 1.0; s_var <- 0.06; is_cov <- -0.12
  # covariate (cov) effect on i and s (signs chosen so one level
  # reproduces a clear direction in the demo)
  gi <- c(G1 = 0.224, G2 = -0.193, G3 = 0.257, G4 = 0.545)
  gs <- c(G1 = -0.049, G2 = -0.026, G3 = -0.140, G4 = -0.189)

  # single-item baseline by group (higher groups higher -> demo of an
  # intercept gap that can break scalar invariance in real data)
  z_i <- c(G1 = 62, G2 = 66, G3 = 72, G4 = 74)
  z_s <- c(G1 = 0.40, G2 = 0.50, G3 = 0.45, G4 = 0.45)

  rows <- list(); id <- 0
  for (g in names(grp_prop)) {
    ng <- n_grp[g]
    cov <- sample(c("M", "F"), ng, replace = TRUE, prob = c(0.5, 0.5))
    female <- (cov == "F") * 1L
    Sigma <- matrix(c(i_var, is_cov, is_cov, s_var), 2, 2)
    z <- MASS::mvrnorm(ng, mu = c(0, 0), Sigma = Sigma)
    i0 <- i_mean[g] + gi[g] * female + z[, 1]
    s0 <- s_mean[g] + gs[g] * female + z[, 2]
    t <- 0:3
    e <- matrix(rnorm(ng * 4, 0, sqrt(0.3)), ng, 4)
    Y <- outer(i0, rep(1, 4)) + outer(s0, t) + e
    Z <- outer(z_i[g] + 2 * female, rep(1, 4)) +
           outer(rep(z_s[g], ng), t) +
           matrix(rnorm(ng * 4, 0, 0.8), ng, 4)
    rows[[g]] <- data.frame(
      id = (id + 1L):(id + ng),
      cov, grp = g,
      y_1 = Y[, 1], y_2 = Y[, 2], y_3 = Y[, 3], y_4 = Y[, 4],
      z_1 = Z[, 1], z_2 = Z[, 2], z_3 = Z[, 3], z_4 = Z[, 4]
    )
    id <- id + ng
  }
  dat <- do.call(rbind, rows)
  dat$grp <- factor(dat$grp, levels = c("G1", "G2", "G3", "G4"))
  dat$cov <- factor(dat$cov, levels = c("M", "F"))
  if (verbose) cat("Synthetic data generated:", nrow(dat), "subjects x 4 waves.\n")
  dat
}

dat <- simulate_data()
head(dat)


## ---------- 2. Data cleaning (three-step, mirrored from a real pipeline) ----------
#' In a real study this step removes implausible group labels, drops
#' invalid tracking, and recodes intermittent outliers as missing
#' (FIML-friendly). For synthetic data we only demonstrate the *shape*
#' of the pipeline.
clean_data <- function(d) {
  # Step 1: valid baseline grouping already encoded in `grp`
  # Step 2: keep subjects with >=1 valid observation per core dimension
  #         (synthetic data is complete, so this is a no-op here)
  # Step 3: boxplot outlier -> recode as NA (illustrative). We use a 3*IQR
  #         fence (instead of the usual 1.5) so the *demo* never produces a
  #         fully-empty row, which would otherwise be dropped by FIML and
  #         could destabilise the MLR estimator. Swap to 1.5 for your real
  #         data if that is your documented cleaning rule.
  for (v in c("y_1", "y_2", "y_3", "y_4",
              "z_1", "z_2", "z_3", "z_4")) {
    q <- quantile(d[[v]], c(0.25, 0.75), na.rm = TRUE)
    iqr <- q[2] - q[1]
    lo <- q[1] - 3 * iqr; hi <- q[2] + 3 * iqr
    d[[v]][d[[v]] < lo | d[[v]] > hi] <- NA
  }
  d
}
dat <- clean_data(dat)


## ---------- 3. MG-LGCM: composite outcome y ----------
#' Linear latent growth model: intercept (i) and slope (s) with fixed
#' loadings 0/1/2/3. Fitted with MLR + FIML (handles non-normality &
#' missing-at-random).
growth <- '
  i =~ 1*y_1 + 1*y_2 + 1*y_3 + 1*y_4
  s =~ 0*y_1 + 1*y_2 + 2*y_3 + 3*y_4
  i ~ 1
  s ~ 1
  i ~~ i
  s ~~ s
  i ~~ s
'

# 3a. Unconditional model on the full sample (no grouping)
fit_total <- growth(growth, missing = "fiml", data = dat, estimator = "MLR")
cat("\n=== Unconditional linear LGCM (total sample) ===\n")
fitMeasures(fit_total, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr"))
parameterestimates(fit_total, standardized = TRUE) |>
  dplyr::filter(lhs %in% c("i", "s"), (op == "~1") | (op == "~" & rhs == "1")) |>
  dplyr::select(lhs, est, se, pvalue, ci.lower, ci.upper)

# 3b. Multi-group baseline (all parameters free) -> reference model
fit_base <- growth(growth, missing = "fiml", data = dat, group = "grp", estimator = "MLR")
cat("\n=== Multi-group baseline model (free) ===\n")
fitMeasures(fit_base, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr"))

# per-group latent means
gm <- parameterestimates(fit_base, standardized = TRUE) |>
  dplyr::filter(lhs %in% c("i", "s"), (op == "~1") | (op == "~" & rhs == "1")) |>
  dplyr::select(group, lhs, est, se, pvalue) |>
  dplyr::arrange(group, lhs)
print(gm)


## ---------- 4. CORRECTED DEMO (a): full measurement-invariance sequence ----------
#' Latent-mean comparison across groups REQUIRES at least scalar
#' (strong) invariance. We demonstrate the complete chain on a single
#' item (z) treated as 4 indicators of a "z" factor across groups.
#' Report configural -> metric -> scalar -> strict and check that scalar
#' fit is acceptable BEFORE comparing latent means.
run_invariance <- function(d) {
  # Full measurement-invariance sequence implemented manually with lavaan::cfa
  # (avoids dependency on semTools::measurementInvariance naming across versions).
  # Levels: configural -> metric (equal loadings) -> scalar (equal loadings +
  # intercepts) -> strict (equal loadings + intercepts + residuals).
  model <- ' z =~ 1*z_1 + z_2 + z_3 + z_4 '
  cfg <- cfa(model, data = d, group = "grp", estimator = "MLR", missing = "fiml")
  met <- cfa(model, data = d, group = "grp", estimator = "MLR", missing = "fiml",
             group.equal = "loadings")
  sca <- cfa(model, data = d, group = "grp", estimator = "MLR", missing = "fiml",
             group.equal = c("loadings", "intercepts"))
  str <- cfa(model, data = d, group = "grp", estimator = "MLR", missing = "fiml",
             group.equal = c("loadings", "intercepts", "residuals"))
  cat("=== Measurement invariance tests (z ~ grp) ===\n")
  print(lavTestLRT(cfg, met, sca, str))
  fm <- rbind(
    fitMeasures(cfg, c("cfi", "tli", "rmsea", "srmr")),
    fitMeasures(met, c("cfi", "tli", "rmsea", "srmr")),
    fitMeasures(sca, c("cfi", "tli", "rmsea", "srmr")),
    fitMeasures(str, c("cfi", "tli", "rmsea", "srmr"))
  )
  rownames(fm) <- c("configural", "metric", "scalar", "strict")
  cat("Fit indices by invariance level (CFI/TLI >= 0.90, RMSEA/SRMR lower = better):\n")
  print(fm)
  invisible(list(cfg = cfg, met = met, sca = sca, str = str))
}
cat("\n=== CORRECTED DEMO (a): measurement invariance (z ~ grp) ===\n")
inv <- run_invariance(dat)


## ---------- 5. Omnibus & pairwise between-group comparisons ----------
#' Satorra-Bentler scaled chi-square (automatic under MLR via lavTestLRT).
#' Latent-mean equality across groups is tested with group.equal = "means"
#' (this constrains the latent intercept/slope means, which is what we want;
#'  "intercepts" would only constrain the already-fixed observed intercepts
#'  and therefore do nothing in a growth() model).
fit_eqmean <- growth(growth, missing = "fiml", data = dat, group = "grp",
                  estimator = "MLR", group.equal = "means")
cat("\n=== Omnibus test: equal latent means across groups (Model 3, joint) ===\n")
print(lavTestLRT(fit_base, fit_eqmean))

# Models 1 & 2 (partial): equal intercept means only / equal slope means only.
# Use group.partial to free the other latent mean from the equality constraint.
cat("\n=== Partial tests: Model 1 (equal i means) & Model 2 (equal s means) ===\n")
for (nm in c("i", "s")) {
  other <- if (nm == "i") "s" else "i"
  m <- tryCatch(
    growth(growth, missing = "fiml", data = dat, group = "grp",
           estimator = "MLR", group.equal = "means",
           group.partial = paste0(other, " ~ 1")),
    error = function(e) { message("  (skipped: ", conditionMessage(e), ")"); NULL })
  if (!is.null(m)) {
    cat("Model", if (nm == "i") "1" else "2", "(", nm, "means equal):\n")
    print(lavTestLRT(fit_base, m))
  }
}

# Pairwise omnibus per group pair (refit 2-group models, scaled LRT)
pairs <- utils::combn(levels(dat$grp), 2, simplify = FALSE)
pair_res <- lapply(pairs, function(p) {
  sub <- dat[dat$grp %in% p, ]
  sub$grp <- droplevels(sub$grp)   # drop unused levels so lavaan sees exactly 2 groups
  f0 <- growth(growth, missing = "fiml", data = sub, group = "grp", estimator = "MLR")
  f1 <- growth(growth, missing = "fiml", data = sub, group = "grp", estimator = "MLR",
            group.equal = "means")
  # lavaan 0.7-2: lavTestLRT() returns the comparison data.frame directly
  # (class c("anova","data.frame")); the difference stats are in columns of
  # row 2 (the constrained model). No $Difftest slot exists in this version.
  lr <- tryCatch(lavTestLRT(f0, f1),
                 error = function(e) { message("  pair ", paste(p, collapse = " vs "),
                                               " skipped: ", conditionMessage(e)); NULL })
  if (is.null(lr) || nrow(lr) < 2L) return(NULL)
  data.frame(pair = paste(p, collapse = " vs "),
             chisq_diff = lr$`Chisq diff`[2],
             df_diff    = lr$`Df diff`[2],
             p_value    = lr$`Pr(>Chisq)`[2],
             stringsAsFactors = FALSE)
})
pair_res <- Filter(Negate(is.null), pair_res)
pair_df <- do.call(rbind, pair_res)
cat("\n=== Pairwise comparisons (joint equal means) ===\n")
print(pair_df)


## ---------- 6. CORRECTED DEMO (b): linear vs quadratic growth ----------
#' A four-wave panel may hide a non-monotonic trajectory if the slope is
#' forced to be linear. Compare linear vs quadratic.
growth_q <- '
  i =~ 1*y_1 + 1*y_2 + 1*y_3 + 1*y_4
  s =~ 0*y_1 + 1*y_2 + 2*y_3 + 3*y_4
  q =~ 0*y_1 + 1*y_2 + 4*y_3 + 9*y_4
  i ~ 1; s ~ 1; q ~ 1
  i ~~ i; s ~~ s; q ~~ q; i ~~ s; i ~~ q; s ~~ q
'
fit_quad <- growth(growth_q, missing = "fiml", data = dat, group = "grp", estimator = "MLR")
cat("\n=== CORRECTED DEMO (b): linear vs quadratic (scaled LRT) ===\n")
print(lavTestLRT(fit_base, fit_quad))


## ---------- 7. Covariate moderation ----------
#' Regress i and s on cov within each group.
growth_g <- '
  i =~ 1*y_1 + 1*y_2 + 1*y_3 + 1*y_4
  s =~ 0*y_1 + 1*y_2 + 2*y_3 + 3*y_4
  i ~ 1 + cov
  s ~ 1 + cov
  i ~~ i; s ~~ s; i ~~ s
'
fit_g <- growth(growth_g, missing = "fiml", data = dat, group = "grp", estimator = "MLR")
cat("\n=== Covariate moderation (i/s ~ cov, by group) ===\n")
parameterestimates(fit_g, standardized = TRUE) |>
  dplyr::filter(op == "~", rhs == "cov") |>
  dplyr::select(group, lhs, est, se, pvalue) |>
  dplyr::arrange(group, lhs) |>
  print()


## ---------- 8. (Optional) quick trajectory plot ----------
#' Lightweight static plot of group-mean outcome trajectories. For publication,
#' use a proper plotting tool to redraw model-implied trajectories.
#' In RStudio the figure prints to the plot pane; under a headless Rscript
#' (no display device) we instead save a PNG, so the run never aborts and
#' leaves no stray Rplots.pdf.
if (require(ggplot2)) {
  traj <- do.call(rbind, lapply(levels(dat$grp), function(g) {
    sub <- dat[dat$grp == g, ]
    m <- colMeans(sub[, paste0("y_", 1:4)], na.rm = TRUE)
    data.frame(grp = g, wave = 1:4, outcome = as.numeric(m),
               stringsAsFactors = FALSE)
  }))
  p <- ggplot(traj, aes(x = wave, y = outcome, color = grp, group = grp)) +
         geom_line() + geom_point() +
         labs(title = "Mean outcome trajectory by group (synthetic demo)",
              x = "Wave", y = "Outcome") + theme_minimal()
  if (interactive()) {
    print(p)
  } else {
    ggsave("outcome_trajectory_by_group.png", p, width = 7, height = 4.5)
    message("  figure saved to outcome_trajectory_by_group.png (headless run)")
  }
}


## ---------- 9. How to point this at YOUR data ----------
#' 1. Replace simulate_data() with a loader that returns a data.frame with
#'    columns: id, cov (M/F), grp (factor, 4 levels), and y_1..y_4
#'    (plus any per-item waves you want to model, e.g. z_1..z_4).
#' 2. Keep sections 2-8 unchanged. FIML handles missingness; if your data
#'    has intermittent outliers, section 2 already recodes them as NA.
#' 3. The PRODUCTION-READY data format and a realistic sample dataset are in
#'    the paid bundle (5-yuan add-on) -- start there when wiring your own data.
#' 4. Before publishing any output, re-run RELEASE_CHECKLIST.md and confirm
#'    no real records are embedded.
cat("\nTemplate finished. All data above are synthetic (generic placeholders, generated by simulate_data()).\n")
